---
- hosts: myserver
  become: True
  tasks:
    - name: Display a msg
      debug:
        msg: Hi Murthi

    - name: Display the config
      debug:
        msg: The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}
...